### ISSUE TITLE
Server access is removed when running PAL docker

### ISSUE THREAD

**Issue by Metuant** [RemiRigal/Plex-Auto-Languages#18]
When running PAL docker I lose the ability to "see" my Plex server via app.plex.tv and local connection. Stopping the container allows access to the server. Config.yaml (redacted token info) and docker-compose config are below.

```
plexautolanguages:
  # Update language for the entire show or only for the current season
  # Accepted values:
  #   - show (default)
  #   - season
  update_level: "show"

  # Update all episodes of the show/season or only the next ones
  # Accepted values:
  #   - all (default)
  #   - next
  update_strategy: "all"

  # Whether or not playing a file should trigger a language update, defaults to 'true'
  trigger_on_play: true

  # Whether or not navigating the Plex library should trigger a language update, defaults to 'false'
  # Set this to 'true' only if you want to perform changes whenever the default track of an episode is updated, even when the episode is not played.
  # Setting this parameter to 'true' can result in higher resource usage.
  trigger_on_activity: false

  # Plex configuration
  plex:
    # A valid Plex URL (required)
    url: "http://plex:32400"
    # A valid Plex Token (required)
    token: "XXXXXXX"

  scheduler:
    # Whether of not to enable the scheduler, defaults to 'true'
    # The scheduler will perform a deeper analysis of all recently played TV Shows
    enable: false
    # The time at which the scheduler start its task with the format 'HH:MM', defaults to '02:00'
    schedule_time: "07:00"

   notifications:
    # Whether of not to enable the notifications through Apprise, defaults to 'false'
    # A notification is sent whenever a language change is performed
    enable: false
    # An array of Apprise configurations, see Apprise docs for more information: https://github.com/caronc/apprise
    apprise_configs:
      - "XXXXXX"
```

Compose config
```
### PAL###
  PAL:
    image: remirigal/plex-auto-languages:latest
    container_name: PAL
    environment:
      - TZ=${TZ}
    volumes:
      - ${APPDATA_ROOT}/PAL/config.yaml:/config/config.yaml
    restart: unless-stopped
```
