### ISSUE TITLE
[Enhancement] Improve notification system

### ISSUE THREAD

**Issue by RemiRigal** [RemiRigal/Plex-Auto-Languages#28]
The current notification system can result in a lot of notifications for people having a lot of users on their servers.

Possible improvements:
- As suggested in #26, notifications for newly added episodes should not be sent per-user.
- Improve the configuration and add Apprise configs for specific users, something like this:
```yaml
notifications:
  enable: true
  apprise_configs:
    - "spush://apikey"
    - urls:
        - "discord://webhook_id/webhook_token"
        - "pover://user@token"
      users:
        - "MyUsername"
        - "MyUser1"
    - urls:
        - "gotify://hostname/token"
      users:
        - "MyUser2"
```

I'm open to feedback and suggestions !
