### ISSUE TITLE
High CPU usage when Plex is detecting intros

### ISSUE THREAD

**Issue by ljo123** [RemiRigal/Plex-Auto-Languages#44]
For some reason I'm getting very high CPU usage when Plex is doing a large scan and detecting intros on newly added media. Running the command `docker stats -a` was showing 60% under CPU % for plex-auto-languages alone. Stopping and restarting the container reset things and CPU usage when down to less than 1%. Anyone else seen this? Configuration file options were left at defaults. This is running in docker on win10.

**Comment by RemiRigal** [comment]
The high CPU usage you observe is probably due to the library scan done by PlexAutoLanguages after Plex scans, I suppose that you have a really large library ? If it's the case, you should probably set the parameter `refresh_library_on_scan` to `false`.

Here is an extract of the mentioned configuration option:
```yaml
plexautolanguages:
  [...]

  # Whether or not to refresh the cached library whenever the Plex server scans its own library, defaults to 'true'
  # Disabling this parameter will prevent PlexAutoLanguages from detecting updated files for an already existing episode
  # It is recommended to disable this parameter if you have a large TV Show library (10k+ episodes)
  refresh_library_on_scan: true

  [...]
```
