### ISSUE TITLE
[ERROR] A Plex Token is required – However, the token is supplied?

### ISSUE THREAD

**Issue by m04ndj5xc2u3pn4eow** [RemiRigal/Plex-Auto-Languages#84]
Hi @RemiRigal , just want to say this is an awesome project!

I'm running into an issue where every time I make changes to the container, (in this case, there was an update recently for this image), and need to restart, it can't find the token. This container was running correctly previously. I also ran into this issue when I restart the container previously. It took a couple of restarts and it just started working.

Server: Synology 920+
Version: 7.2-64570

Error Log:
```
stdout	plex_auto_languages.exceptions.InvalidConfiguration
stdout	    raise InvalidConfiguration
stdout	  File "/app/plex_auto_languages/utils/configuration.py", line 113, in _validate_config
stdout	    self._validate_config()
stdout	  File "/app/plex_auto_languages/utils/configuration.py", line 74, in __init__
stdout	    self.config = Configuration(user_config_path)
stdout	  File "main.py", line 27, in __init__
stdout	    plex_auto_languages = PlexAutoLanguages(args.config_file)
stdout	  File "main.py", line 117, in <module>
stdout	Traceback (most recent call last):
stdout	[ERROR] A Plex Token is required
stdout	[INFO] Setting value of parameter PLEX_URL from environment variable
```

docker-compose.yml:
```
  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    secrets:
      - plex_token
    environment:
      - TZ=Europe/Paris
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN_FILE=/run/secrets/plex_token
    volumes:
      - /volume1/docker/plexautolanguages:/config
    restart: unless-stopped

secrets:
  plex_token:
    file: /volume1/docker/plexautolanguages/secrets/plex_token
```

Can you advise? Maybe my setup is incorrect for how it reads the token? But, then how does it work when it is able to read the token?
